services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - postgres
    restart: unless-stopped
  api:
    container_name: weather_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: '${POSTGRES_PORT:-5432}'
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      OPEN_WEATHER_API_URL: ${OPEN_WEATHER_API_URL}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
    ports:
      - '${API_PORT:-3000}:3000'
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:

networks:
  postgres:
